import type { Metadata } from 'next'
import { Amplify } from 'aws-amplify'

import ConfigureAmplifyClientSide from './components/ConfigureAmplify'

import { config } from '@/../awsconfig'
import '@aws-amplify/ui-react/styles.css'

Amplify.configure(config)
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<ConfigureAmplifyClientSide />

			<body>{children}</body>
		</html>
	)
}